<a href="https://colab.research.google.com/github/CE605A/Mriganka-Shekhar-Barman_231030038/blob/main/Mriganka_605A_231030038_A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# question - 1



#create a row vector
import numpy as np   #importing numpy
row = np.array([12, 24, 36, 48, 60])
print("row:")
print(row)

#create a column vector
column = np.array([[72],
[84],
[96],
[108],
[120]])
print("column:")
print(column)


row:
[12 24 36 48 60]
column:
[[ 72]
 [ 84]
 [ 96]
 [108]
 [120]]


In [ ]:
# question - 2



# Manually creating a 5x5 matrix
import numpy as np
a = np.array([[10, 20, 30, 40, 50],
[60, 70, 80, 90, 100],
[110, 120, 130, 140, 150],
[160, 170, 180, 190, 200],
[210, 220, 230, 240, 250]])
print("Matrix 'a' manually:")
print(a)


# create a 5x5 matrix by input method
import numpy as np
a_inp = np.zeros((5, 5)) # Initializing with zeros

print("Enter values of the matrix (5x5):")
for i in range(5):
    for j in range(5):
         a_inp[i, j] = float(input(f"Enter value for element at position ({i+1}, {j+1}): "))
print("Matrix 'a' by input method:")
print(a_inp)


Matrix 'a' manually:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]
Enter values of the matrix (5x5):
Enter value for element at position (1, 1): 1
Enter value for element at position (1, 2): 2
Enter value for element at position (1, 3): 3
Enter value for element at position (1, 4): 4
Enter value for element at position (1, 5): 5
Enter value for element at position (2, 1): 6
Enter value for element at position (2, 2): 7
Enter value for element at position (2, 3): 8
Enter value for element at position (2, 4): 9
Enter value for element at position (2, 5): 10
Enter value for element at position (3, 1): 11
Enter value for element at position (3, 2): 12
Enter value for element at position (3, 3): 13
Enter value for element at position (3, 4): 14
Enter value for element at position (3, 5): 15
Enter value for element at position (4, 1): 16
Enter value for element at position (4, 2): 17
Enter value for element at position (4,

In [ ]:
# Question - 3



# Extracting the 3rd row (index 2, since indexing starts from 0)

import numpy as np
a = np.array([[0, 1, 1, 2, 3],
[5, 8, 13, 21, 34],
[55, 89, 144, 233, 377],
[610, 987, 1597, 2584, 4181],
[6765, 10946, 17711, 28657, 46368]])
third_row = a[2, :]       #extracting the 3rd row
print("3rd Row of the Matrix:")
print(third_row)


3rd Row of the Matrix:
[ 55  89 144 233 377]


In [ ]:
# Question-4



# Extracting the 4th column (index 3, since indexing starts from 0)

fourth_column = a[:, 3]       #extracting the 4th column
print("4th Column of the Matrix:")
print(fourth_column)

4th Column of the Matrix:
[    2    21   233  2584 28657]


In [ ]:
# QUESTION - 5



# Sorting row-wise
sorted_rows = np.sort(a, axis=1)

# Sorting column-wise
sorted_columns = np.sort(a, axis=0)

print("Original Matrix:")
print(a)

print("\nMatrix with Sorted Rows:")
print(sorted_rows)

print("\nMatrix with Sorted Columns:")
print(sorted_columns)


Original Matrix:
[[    0     1     1     2     3]
 [    5     8    13    21    34]
 [   55    89   144   233   377]
 [  610   987  1597  2584  4181]
 [ 6765 10946 17711 28657 46368]]

Matrix with Sorted Rows:
[[    0     1     1     2     3]
 [    5     8    13    21    34]
 [   55    89   144   233   377]
 [  610   987  1597  2584  4181]
 [ 6765 10946 17711 28657 46368]]

Matrix with Sorted Columns:
[[    0     1     1     2     3]
 [    5     8    13    21    34]
 [   55    89   144   233   377]
 [  610   987  1597  2584  4181]
 [ 6765 10946 17711 28657 46368]]


In [ ]:
# Question - 6

# if element is greater than 2, multiply element by 10


# Initializing an empty matrix 'b' to store the result
b = np.zeros_like(a)

# Applying the condition and multiplication using a for loop

for i in range(a.shape[0]): # Iterate over rows
    for j in range(a.shape[1]): # Iterate over columns
        if a[i, j] > 2:
           b[i, j] = a[i, j] * 10
        else:
            b[i, j] = a[i, j]

print("Original Matrix:")
print(a)
print("\nMatrix 'b' after Multiplication:")
print(b)


Original Matrix:
[[    0     1     1     2     3]
 [    5     8    13    21    34]
 [   55    89   144   233   377]
 [  610   987  1597  2584  4181]
 [ 6765 10946 17711 28657 46368]]

Matrix 'b' after Multiplication:
[[     0      1      1      2     30]
 [    50     80    130    210    340]
 [   550    890   1440   2330   3770]
 [  6100   9870  15970  25840  41810]
 [ 67650 109460 177110 286570 463680]]


In [ ]:
# Question - 7



# Adding matrices 'a' and 'b'

print("Matrix 'a':")
print(a)
print("\nMatrix 'b':")
print(b)

result = a + b # adding the matrices

print("\nMatrix 'a + b':")
print(result)

Matrix 'a':
[[    0     1     1     2     3]
 [    5     8    13    21    34]
 [   55    89   144   233   377]
 [  610   987  1597  2584  4181]
 [ 6765 10946 17711 28657 46368]]

Matrix 'b':
[[     0      1      1      2     30]
 [    50     80    130    210    340]
 [   550    890   1440   2330   3770]
 [  6100   9870  15970  25840  41810]
 [ 67650 109460 177110 286570 463680]]

Matrix 'a + b':
[[     0      2      2      4     33]
 [    55     88    143    231    374]
 [   605    979   1584   2563   4147]
 [  6710  10857  17567  28424  45991]
 [ 74415 120406 194821 315227 510048]]


In [ ]:
# Question - 8



# Subtracting matrices 'b' to 'a'

print("Matrix 'a':")
print(a)
print("\nMatrix 'b':")
print(b)

result = b - a  # # subtracting the matrices

print("\nMatrix 'b-a':")
print(result)


Matrix 'a':
[[    0     1     1     2     3]
 [    5     8    13    21    34]
 [   55    89   144   233   377]
 [  610   987  1597  2584  4181]
 [ 6765 10946 17711 28657 46368]]

Matrix 'b':
[[     0      1      1      2     30]
 [    50     80    130    210    340]
 [   550    890   1440   2330   3770]
 [  6100   9870  15970  25840  41810]
 [ 67650 109460 177110 286570 463680]]

Matrix 'b-a':
[[     0      0      0      0     27]
 [    45     72    117    189    306]
 [   495    801   1296   2097   3393]
 [  5490   8883  14373  23256  37629]
 [ 60885  98514 159399 257913 417312]]


In [ ]:
# Question -9



# a*b elementwise

print("Matrix 'a':")
print(a)
print("\nMatrix 'b':")
print(b)

result = a * b  # a*b elementwise

print("\nMatrix 'a*b':")
print(result)



# Matrix multiplication of matrices 'a' and 'b'

matrix_multiplication_result = np.dot(a, b)

print("\nMatrix Multiplication (a dot b):")
print(matrix_multiplication_result)

Matrix 'a':
[[    0     1     1     2     3]
 [    5     8    13    21    34]
 [   55    89   144   233   377]
 [  610   987  1597  2584  4181]
 [ 6765 10946 17711 28657 46368]]

Matrix 'b':
[[     0      1      1      2     30]
 [    50     80    130    210    340]
 [   550    890   1440   2330   3770]
 [  6100   9870  15970  25840  41810]
 [ 67650 109460 177110 286570 463680]]

Matrix 'a*b':
[[          0           1           1           4          90]
 [        250         640        1690        4410       11560]
 [      30250       79210      207360      542890     1421290]
 [    3721000     9741690    25504090    66770560   174807610]
 [  457652250  1198149160  3136795210  8212236490 21499914240]]

Matrix Multiplication (a dot b):
[[     215750      349090      564840      913930     1478770]
 [    2435750     3941125     6376875    10318000    16695010]
 [   27009000    43701465    70710465   114411930   185123880]
 [  299534750   484657240   784191990  1268849230  2053057690]
 

In [ ]:
# Question 10
# Define the matrices A and B




A = np.array([[18, 8, 3, 6, 5],
[2, 7, 20, 76, 8],
[76, 9, 24, 85, 54],
[87, 90, 56, 5, 108],
[45, 28, 59, 33, 68]])
B = np.array([[50, 90, 60, 70, 40],
[80, 5, 60, 980, 120],
[670, 90, 560, 140, 970],
[390, 930, 540, 230, 630],
[40, 170, 810, 960, 680]])

# Divide each element of matrix a and b by 18
import numpy as np

# Divide each element by 18
A_divided = A / 18
B_divided = B / 18
print("Matrix A divided by 18:")
print(A_divided)
print("\nMatrix B divided by 18:")
print(B_divided)


Matrix A divided by 18:
[[1.         0.44444444 0.16666667 0.33333333 0.27777778]
 [0.11111111 0.38888889 1.11111111 4.22222222 0.44444444]
 [4.22222222 0.5        1.33333333 4.72222222 3.        ]
 [4.83333333 5.         3.11111111 0.27777778 6.        ]
 [2.5        1.55555556 3.27777778 1.83333333 3.77777778]]

Matrix B divided by 18:
[[ 2.77777778  5.          3.33333333  3.88888889  2.22222222]
 [ 4.44444444  0.27777778  3.33333333 54.44444444  6.66666667]
 [37.22222222  5.         31.11111111  7.77777778 53.88888889]
 [21.66666667 51.66666667 30.         12.77777778 35.        ]
 [ 2.22222222  9.44444444 45.         53.33333333 37.77777778]]


In [ ]:
# Question - 11
# Find the inverse, Rank, Condition number, Singular Value Decomposition and The Norm of Matrices A and B.



# Inverse of matrix A
A_inverse = np.linalg.inv(A)
print("Inverse of Matrix A:")
print(A_inverse)

# Rank of matrix A
rank_A = np.linalg.matrix_rank(A)
print("Rank of Matrix A:", rank_A)

# condition number of matrix A
cond_number_A = np.linalg.cond(A)
print("Condition Number of Matrix A:", cond_number_A)

# Singular value decomposition
U, S, Vt = np.linalg.svd(A)
print("U matrix:")
print(U)
print("Singular Values (Σ matrix):")
print(np.diag(S))
print("V transpose matrix:")
print(Vt)

# the norm of matrix A
norm_A = np.linalg.norm(A)
print("Norm of Matrix A:", norm_A)


# Inverse of matrix B
B_inverse = np.linalg.inv(B)
print("Inverse of Matrix B:")
print(B_inverse)

# Rank of matrix B
rank_B = np.linalg.matrix_rank(B)
print("Rank of Matrix B:", rank_B)

# condition number of matrix B
cond_number_B = np.linalg.cond(B)
print("Condition Number of Matrix B:", cond_number_B)

# Singular value decomposition
U, S, Vt = np.linalg.svd(B)
print("U matrix:")
print(U)
print("Singular Values (Σ matrix):")
print(np.diag(S))
print("V transpose matrix:")
print(Vt)

# the norm of matrix B
norm_B = np.linalg.norm(B)
print("Norm of Matrix B:", norm_B)

Inverse of Matrix A:
[[ 0.06709786 -0.01000392  0.00233646 -0.00726219  0.0059219 ]
 [ 0.0259031   0.01813758 -0.01309691  0.01330015 -0.01476175]
 [ 0.07345776  0.00270836 -0.02050015 -0.01576537  0.0355987 ]
 [-0.01156773  0.01198683  0.00449183  0.00183958 -0.00704836]
 [-0.11319064 -0.00901521  0.01945369  0.01211537 -0.01060124]]
Rank of Matrix A: 5
Condition Number of Matrix A: 36.52754529953281
U matrix:
[[-0.08014042 -0.00812732 -0.20899823 -0.14157668 -0.96425476]
 [-0.1737107  -0.61161562  0.5891618  -0.4974023  -0.03507492]
 [-0.48524205 -0.57235865 -0.62962256  0.11586598  0.16460933]
 [-0.71704216  0.54593729  0.00931713 -0.41790473  0.11433218]
 [-0.46237734 -0.01477595  0.46119055  0.73788733 -0.16974814]]
Singular Values (Σ matrix):
[[229.97419574   0.           0.           0.           0.        ]
 [  0.         103.35849971   0.           0.           0.        ]
 [  0.           0.          39.26627833   0.           0.        ]
 [  0.           0.           0.     

In [ ]:
# Question - 12
# Find the norm, inner product and outer product of column vector



import numpy as np              # Importing numpy
# column vector x
x = np.array([12, 56, 15, 7])

norm_x = np.linalg.norm(x)      # Finding Norm of vector x
print("Norm of Column Vector x:", norm_x)

y = np.array([8, 2, 17, 3])

norm_y = np.linalg.norm(y)      # Finding Norm of vector y
print("Norm of Column Vector y:", norm_y)

inner_product = np.dot(x, y)    # Finding Inner Product
print("Inner Product of Column Vectors x and y:", inner_product)

outer_product = np.outer(x, y)  # Finding Outer Product
print("Outer Product of Column Vectors x and y:")
print(outer_product)

Norm of Column Vector x: 59.61543424315552
Norm of Column Vector y: 19.131126469708992
Inner Product of Column Vectors x and y: 484
Outer Product of Column Vectors x and y:
[[ 96  24 204  36]
 [448 112 952 168]
 [120  30 255  45]
 [ 56  14 119  21]]


In [ ]:
# QUESTION - 13
# Write a function called derivative which takes input parameters f(x), a, method (forward,backward and central) and h(step size) (with default values method=‘central’ and h = 0.01) and returns the corresponding difference formula for derivative of function at a with step size h and then test your function on e^x and cos x at x = 0.5



import math

def derivative(f, a, method='central', h=0.01):
    # the numerical derivative using different methods.
    # Returns the approximate derivative of function f at point a.

    if method == 'forward':
        return (f(a + h) - f(a)) / h
    elif method == 'backward':
        return (f(a) - f(a - h)) / h
    elif method == 'central':
        return (f(a + h) - f(a - h)) / (2 * h)
    else:
        raise ValueError("Invalid method, supported methods are 'forward', 'backward', and 'central'.")

    def ex(x):
        return math.exp(x)

    def cos(x):
        return math.cos(x)


    x = 0.5                                               # value of x is intialized

    ex_forward = derivative(ex, x, method='forward')      # for x =0.5 forward derivative ex()
    ex_backward = derivative(ex, x, method='backward')    #for x =0.5 backward derivative ex()
    ex_central = derivative(ex, x, method='central')      #for x =0.5 central derivative ex()

    cos_forward = derivative(cos, x, method='forward')    #for x =0.5 forward derivative cos()
    cos_backward = derivative(cos, x, method='backward')  #for x =0.5 backward derivative is cos()
    cos_central = derivative(cos, x, method='central')    #for x =0.5 backward derivative cos()

    print("Testing on ex(x) at x =",x)
    print("Forward difference:", ex_forward)
    print("Backward difference:", ex_backward)
    print("Central difference:", ex_central)

    print("\nTesting on cos(x) at x =",x)
    print("Forward difference:", cos_forward)
    print("Backward difference:", cos_backward)
    print("Central difference:", cos_central)

In [ ]:
# QUESTION - 14
# Download the Automatic Weather Station AWS Data. Read the .csv file using pandas library as a DataFrame

import pandas as pd
# Dowloaded an aws_file from google and save it as .csv
df = pd.read_csv('/Assignment1/aws_sept14.csv', index_col=0) # path of the file
print(df)

            longitude   latitude start_year  end_year  status  aws  reg_name  \
rainfall_s                                                                     
Dollow      42.079382   4.187771   Mar 2014       0.0     0.0  0.0       0.0   
Boroma      43.179160   9.940072   Oct 2010       0.0     0.0  0.0       0.0   
Burao       45.566670   9.516670  Sept 2014       0.0     0.0  0.0       0.0   
Erigavo     47.366670  10.616670       2009       0.0     0.0  0.0       0.0   
Hargeisa    44.066800   9.559750       2008       0.0     0.0  0.0       0.0   
Aburin      43.805750   9.517430       2012       0.0     0.0  0.0       0.0   
Galkayo     47.422720   6.777190       2012       0.0     0.0  0.0       0.0   
Garowe      48.477540   8.404580       2009       0.0     0.0  0.0       0.0   
Burao       45.566670   9.516670       2014       0.0     0.0  0.0       0.0   
Mandera     41.860792   3.934514       2012       0.0     0.0  0.0       0.0   

            dist_name mgt              